services:
  client:
    build:
      context: ./client
    container_name: client
    volumes:
      - ../evaluation/logs/receiver/:/app/evaluation/logs/receiver/
      - ../shared/:/app/shared/:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - ZMQ_PUSH_SOCKET="tcp://decoder:5555"
      - ZMQ_PULL_SOCKET="tcp://decoder:5555"
      - ZMQ_PUSH_SOCKET="tcp://visualizer:5555"
    networks:
      - receiver_network
    ports:
      - "5000:5000"

  decoder:
    build:
      context: ./decoder
    container_name: decoder
    volumes:
      - ../dependencies/unified-compression/:/app/unified/
      - ../shared/:/app/shared/:ro
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - ZMQ_PULL_SOCKET="tcp://client:5555"
      - ZMQ_PUSH_SOCKET="tcp://client:5555"
    networks:
      - receiver_network

  visualizer:
    build:
      context: ./visualizer
    volumes:
      - ../shared/:/app/shared/:ro
    container_name: visualizer
    ports:
      - "5173:5173"
      - "8765:8765"
    environment:
      - ZMQ_PULL_SOCKET="tcp://client:5556"
    networks:
      - receiver_network
    stdin_open: true
    tty: true

networks:
  receiver_network:
    driver: bridge
