services:
  client:
    build:
      context: ./client
    container_name: client
    environment:
      - ZMQ_SOCKET="tcp://decoder:5555"
    networks:
      - receiver_network

  decoder:
    build:
      context: ./decoder
    container_name: decoder
    volumes:
      - ../dependencies/unified-compression/:/app/unified/
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - ZMQ_PULL_SOCKET="tcp://client:5555"
      - ZMQ_PUSH_SOCKET="tcp://visualizer:5556"
    networks:
      - receiver_network

  visualizer:
    build:
      context: ./visualizer
    container_name: visualizer
    ports:
      #- "8080:8080"
      - "5173:5173"
    environment:
      - ZMQ_PULL_SOCKET="tcp://decoder:5556"
    networks:
      - receiver_network

networks:
  receiver_network:
    driver: bridge
