# Server
camera: "zed"
mode: "demo" # "demo", "playback", "recording"
recording_path: "./evaluation/data/title_fig"
depth_clip: 1.4
voxel_size: 0.005
max_points: 30000
max_queue_size: 100
target_fps: 5
segment_duration: 1.0
publish_offset: 3.0
encoding_settings:
  - [1.0, 0.0]
  - [0.0, 1.0]
  - [1, 1]

# Client
decoder_type: "parallel"
request_offset: 0.3
playout_offset: 3.0
init_quality: 2

# ZMQ
capturer_push_address: "tcp://encoder:5555"
encoder_push_address: "tcp://mediaserver:5556"
encoder_pull_address: "tcp://*:5555"
media_server_pull_address: "tcp://*:5556"
client_push_address: "tcp://decoder:5555"
client_pull_address: "tcp://*:5555"
visualizer_push_address: "tcp://visualizer:5556"
decoder_push_address: "tcp://client:5555"
decoder_pull_address: "tcp://*:5555"

# Media Server
ip_addr: "0.0.0.0"
port: 8080
output_directory: "./media"
mpd_url: "http://172.23.181.26:8080/media/manifest.mpd"
