### SENDER ###
# Capturer
camera: "zed"
decimate: 0
depth_clip: -1.0
voxel_size: 0.003
capturer_push_address: "tcp://encoder:5555"

# Encoder
max_queue_size: 100
target_fps: 3
gop_size: 3
segment_duration: 1.0
encoder_push_address: "tcp://mediaserver:5556"
encoder_pull_address: "tcp://*:5555"

# Media Server
media_server_pull_address: "tcp://*:5556"
ip_addr: "0.0.0.0"
port: 8080
output_directory: "./media"


### RECEIVER ###