# Use the official Node.js image as a parent image
FROM node:20

# Prevent interactive prompts during installation
ARG DEBIAN_FRONTEND=noninteractive

# Install Python and required dependencies
RUN apt-get update && apt-get -y install \
    python3 python3-pip python3-venv \
    libtool pkg-config build-essential \
    autoconf automake uuid-dev wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to install Node.js dependencies
COPY package*.json ./

# Install Node.js dependencies
RUN npm install --save three \
    && npm install --save-dev vite


# Create a virtual environment for Python
RUN python3 -m venv /env

# Ensure the virtual environment's pip is up-to-date
RUN /env/bin/pip install --upgrade pip

# Copy the Python requirements file and install Python dependencies in the virtual environment
COPY requirements.txt .
RUN /env/bin/pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project files into the container
COPY . .
COPY ./test_data /app/public/test_data

# Install a lightweight HTTP server globally
RUN npm install -g http-server

# Expose the development server port
EXPOSE 5173

# Default command to run both the Python script and Vite development server
CMD ["sh", "-c", "/env/bin/python pointcloud_tester.py & npx vite --host 0.0.0.0 --port 5173"]
