# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --save three
RUN npm install --save-dev vite

# Copy the project files into the container
COPY . .
COPY ./test_data /app/public/test_data

# Expose the development server port
EXPOSE 5173

# Default command to run the development server
CMD ["npx", "vite", "--host"]
